version: "2.4"

services:
  frontend:
    image: sandilembatha/vending-machine-ui
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: npm start

  backend:
    image: sandilembatha/vending-machine-api
    restart: unless-stopped
    ports:
      - "8080:8080"
   