# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      env:
          DOCKER_TOKEN: ${{ env.DOCKER_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22
      
    - run: |
       git config user.name "GitHub Actions Bot"
       git config user.email "<>"     
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test
    - run: git push
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
          image: sandilembatha/vending-machine-ui
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

